### ISSUE TITLE
Research the Zoom SDK and WebRTC

### ISSUE THREAD

**Issue by jake-pauls** [jake-pauls/babble#1]
**Overview**
To provision video/audio across web sockets, an SDK or platform is required. Take a look at both the [Zoom SDK](https://marketplace.zoom.us/docs/sdk/native-sdks/introduction) and [WebRTC](https://webrtc.org/) and figure out which one is better suited for our project.

**Comment by jake-pauls** [comment]
Stumbled upon [PeerJS](https://peerjs.com/), a wrapper for WebRTC. Might be worth investigating if the two options above aren't feasible.

**Comment by AirinB** [comment]
@jake-pauls I think a zoom SDK is a very good option and it's a great and easy option, works just out of the box and has a lot of useful features. [This page](https://marketplace.zoom.us/docs/sdk/native-sdks/web) is so useful for setting up.
