### ISSUE TITLE
[FEAT] Implement web sockets and their implementation in both the code editor and video call system

### ISSUE THREAD

**Issue by jake-pauls** [jake-pauls/babble#12]
**Overview**
For pair programming sessions, we don't have any way to dynamically move peers between 'rooms' in the app for their sessions. Any code editor implementation might also not work due to this. 

**Proposed Solution**
Add [Socket.io](https://socket.io/) events to the backend that manage people in a 'room'-like fashion and pair people up once they've connected to our peer network.

**Comment by bootsie123** [comment]
The first basic implementation is down! It probably good be improved a lot more though

**Comment by bootsie123** [comment]
Looks like I forgot that CORS was a thing. I'll add a fix for it soon.

EDIT: Issue fixed
