### ISSUE TITLE
[FEAT] Create vue app and investigate vercel deployment

### ISSUE THREAD

**Issue by jake-pauls** [jake-pauls/babble#4]
**Overview**
Create a basic vue template app that's hooked up to a Vercel deployment.

**Proposed Solution**
 Using [Vercel/Vue](https://vercel.com/solutions/vue) create a basic app, already deployed from our `main` branch.

**Why Vercel?**
If deployed, Vercel can provide preview URLs for PRs so we can quickly see how each other's changes would act in production. This would be a simpler way to test/demo our app as well as also save time towards the end of the week if we want to focus on any deployments.

**Comment by homa31** [comment]
I can try looking into this since it doesn't seem too complicated, how soon does this need to be done?

**Comment by jake-pauls** [comment]
I was going to do this super quick tonight, but if you'd like to, go for it! It shouldn't take long.
I was just going to initialize/put the Vue app in a `client` or `frontend` folder and then deploy that app to Vercel.

**Comment by homa31** [comment]
If that is the case, it's probably faster and better if you do it instead.

**Comment by homa31** [comment]
Thanks by the way!
